apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: user-password
spec: {}
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: long-user-password
spec:
  length: 124
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: postgresql-password
spec:
  secretTemplate:
    type: Opaque
    stringData:
      postgresql-password: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: complex-password
spec:
  length: 27
  digits: 2
  uppercaseLetters: 4
  lowercaseLetters: 10
  symbols: 3
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: symbol-only-password
spec:
  length: 7
  symbols: 7
  symbolCharSet: "!$#%"
---

